# Site settings
title: David Dooling's Blog
description: >
  The nexus of Politics, Information Technology, and other random things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ddgenome.github.io"
header-img: "img/array-bg.jpg"
twitter_username: ddgenome
github_username: ddgenome

# Build settings
markdown: kramdown
paginate: 5
permalink: /:year/:month/:title/
exclude:
  - README.md
  - Gemfile*
  - LICENSE
  - less
  - "*.hide"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
