# Site settings
title: PolITiGenomics
description: > # this means to ignore newlines until "baseurl:"
  The nexus of Politics, Information Technology, and Genomics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.politigenomics.com" # the base hostname & protocol for your site
header-img: "img/array-bg.jpg"
twitter_username: ddgenome
github_username: ddgenome

# Build settings
markdown: kramdown
paginate: 5
#permalink: /:year/:month/:title/
exclude:
  - "README.md"
  - "Gemfile*"
  - "LICENSE"
  - "jekyll-clean-front-matter.rb"
  - "less"
  - "*.hide"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
